const BROWSER_SUPPORTED_PHOTO_EXTS = /(jpg|jpeg|png|gif)$/i
const BROWSER_SUPPORTED_VIDEO_EXTS = /(mp4)$/i
const BROWSER_CONVERTED_PHOTO_EXT = 'jpg'
const BROWSER_CONVERTED_VIDEO_EXT = 'mp4'

module.exports = {
  BROWSER_SUPPORTED_PHOTO_EXTS,
  BROWSER_SUPPORTED_VIDEO_EXTS,
  BROWSER_CONVERTED_PHOTO_EXT,
  BROWSER_CONVERTED_VIDEO_EXT,
}